import { Roboto, Playfair_Display, Dancing_Script } from "next/font/google";
import "@/app/globals.css";
import Navbar from "./_components/nav/Navbar";
import Footer from "./_components/Footer";

const roboto = Roboto({
  variable: "--font-roboto",
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
});
const dancingScript = Dancing_Script({
  variable: "--font-dancing-Script",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${playfairDisplay.variable} ${dancingScript.variable} h-full antialiased `}
    >
      <Navbar />
      <body className="min-h-full flex flex-col font-roboto">{children}</body>
      <Footer />
    </html>
  );
}
